# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Zybo-Z7-ExtensionAffichage.xdc

# Block Designs: bd/Projet/Projet.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Projet || ORIG_REF_NAME==Projet} -quiet] -quiet

# IP: bd/Projet/ip/Projet_xlconstant_0_0/Projet_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Projet_xlconstant_0_0 || ORIG_REF_NAME==Projet_xlconstant_0_0} -quiet] -quiet

# IP: bd/Projet/ip/Projet_Chronometre_0_0/Projet_Chronometre_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Projet_Chronometre_0_0 || ORIG_REF_NAME==Projet_Chronometre_0_0} -quiet] -quiet

# IP: bd/Projet/ip/Projet_BaseDeTemps_0_0/Projet_BaseDeTemps_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Projet_BaseDeTemps_0_0 || ORIG_REF_NAME==Projet_BaseDeTemps_0_0} -quiet] -quiet

# IP: bd/Projet/ip/Projet_Aff_7seg_0_0/Projet_Aff_7seg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Projet_Aff_7seg_0_0 || ORIG_REF_NAME==Projet_Aff_7seg_0_0} -quiet] -quiet

# IP: bd/Projet/ip/Projet_Gestion_Mode_0_0/Projet_Gestion_Mode_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Projet_Gestion_Mode_0_0 || ORIG_REF_NAME==Projet_Gestion_Mode_0_0} -quiet] -quiet

# IP: bd/Projet/ip/Projet_Minuteur_0_0/Projet_Minuteur_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Projet_Minuteur_0_0 || ORIG_REF_NAME==Projet_Minuteur_0_0} -quiet] -quiet

# IP: bd/Projet/ip/Projet_Alarm_0_0/Projet_Alarm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Projet_Alarm_0_0 || ORIG_REF_NAME==Projet_Alarm_0_0} -quiet] -quiet

# IP: bd/Projet/ip/Projet_Horloge_0_0/Projet_Horloge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Projet_Horloge_0_0 || ORIG_REF_NAME==Projet_Horloge_0_0} -quiet] -quiet

# XDC: m:/UNI/L2/L2 S4/ELE401/Horloge_ELE401/Horloge_ELE401.gen/sources_1/bd/Projet/Projet_ooc.xdc
