@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Apr 01 10:46:53 +0200 2025
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim TB_Horloge_time_impl -key {Post-Implementation:sim_1:Timing:TB_Horloge} -tclbatch TB_Horloge.tcl -protoinst "protoinst_files/Projet.protoinst" -view M:/UNI/L2/L2 S4/ELE401/Horloge_ELE401/TB_Gestion_Mode_behav.wcfg -view M:/UNI/L2/L2 S4/ELE401/Horloge_ELE401/TB_Minuteur_behav.wcfg -log simulate.log"
call xsim  TB_Horloge_time_impl -key {Post-Implementation:sim_1:Timing:TB_Horloge} -tclbatch TB_Horloge.tcl -protoinst "protoinst_files/Projet.protoinst" -view M:/UNI/L2/L2 S4/ELE401/Horloge_ELE401/TB_Gestion_Mode_behav.wcfg -view M:/UNI/L2/L2 S4/ELE401/Horloge_ELE401/TB_Minuteur_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
